Documents/GitHub/graduation/卒業制作 2020_10_29/flaskr/views.py
from datetime import datetime
import os
from flask import (
    Blueprint, abort, request, render_template,
    redirect, url_for, flash
)
from flask.globals import session
from flask_login import (
    login_user, login_required, logout_user, current_user
)
from flaskr.models import (
    User, PasswordResetToken,Planning_data,Comment_data,Message_data,Planning_menber,
    Planning_chat,Plan_evaluation,User_evaluation
)
from flaskr import db

from flaskr.forms import (
    LoginForm, RegisterForm, ResetPasswordForm,
    ForgotPasswordForm, UserForm, ChangePasswordForm
)

bp = Blueprint('app', __name__, url_prefix='')



course_cr = ['放送芸術科','声優・演劇科','演劇スタッフ科','マンガ・アニメーション科']
course_ds = ['ゲームクリエイター科','CG映像科','デザイン科']
course_mu = ['ミュージックアーティスト科','音響芸術科','コンサート・イベント科','ダンスパフォーマンス科']
course_it = ['ITスペシャリスト科(4年制)','情報処理科','情報ビジネス科','AIシステム科','ネットワークセキュリティ科']
course_tc = ['建築学科(4年制)','建築設計科','機械設計科','電子・電気科']
tagu = ['カメラマン','放送制作','映像編集','放送音声','放送照明','映像美術','声優','俳優・タレント'
    ,'演劇','キャラクターデザイン','マンガ','アニメーション','ゲームプログラマー','ゲームプランナー','ゲームCGデザイナー','ゲームビジネス','CG映像'
,'グラフィックデザイン','イラストレーション','インテリアデザイン','プロダクトデザイン','ギター','ベース','ドラム','キーボード','ヴォーカル','作詞・作曲','TV映像音楽クリエイター',
'ゲーム音楽クリエイター','コンサート制作','コンサートPA','コンサート照明','コンサート舞台','イベント企画','音響芸術','ダンスパフォーマンス','システム','モバイルアプリ','ネットワークセキュリティー','webデザイン','建築設計','機械設計','電子・電気科']
@bp.route('/')
def home():
    #
    plan = Planning_data.select_home()
    end_lists = Planning_data.end_select_home()
    print(plan)
    html = 'home.html'
    return render_template(html,tag=tagu,course_cr=course_cr,course_ds=course_ds,
    course_mu=course_mu,course_it=course_it,course_tc=course_tc,lists=plan,end_lists=end_lists)
    #
    
@bp.route('/練習')
def 練習():
    plan = User.select_all()
    a = Planning_data.select_all()
    create_plan = Planning_data.select_id_by_title("送信練習")
    print(create_plan)
    html = '練習.html'
    picture_path = User.select_picture_path(current_user.id)
    for i in picture_path:
        picture_path = i.picture_path
    return render_template(html, user=plan, a=a, picture_path=picture_path)

@bp.route('/練習_s', methods=["POST"])
def 練習1():
    for i in range(5):
        f = request.form.get(str(i))
        print(f)
    plan = User.select_all()
    a = Planning_data.select_all()
    html = '練習.html'
    picture_path = User.select_picture_path(current_user.id)
    for i in picture_path:
        picture_path = i.picture_path
    return render_template(html, user=plan, a=a, picture_path=picture_path)

@bp.route('/logout')
def logout():
    logout_user() # ログアウト
    return redirect(url_for('app.home'))

@bp.route('/search')
def search():
    html = 'search.html'
    tag = request.args.get('tags')
    print(tag)
    lists = Planning_data.select_search(tag)
    return render_template(html, tag=tag, taglist=tagu, lists=lists)

@bp.route('/planning_list')
@login_required
def planning_list():
    html = 'planning_list.html'
    lists = Planning_data.my_planning_list(current_user.id)
    return render_template(html, lists=lists)

@bp.route('/participation_list')
@login_required
def participation_list():
    html = 'participation_list.html'
    lists = Planning_data.participation_list(current_user.id)
    return render_template(html, lists=lists)

@bp.route('/plan_chat')
@login_required
def plan_chat():
    id = request.args.get('ID')
    check = Planning_menber.check_menber(id,current_user.id)
    lists = Planning_chat.select_plan_chat(id)
    planner = Planning_data.select_planner(id)
    menber_status = Planning_menber.menber_status(id,current_user.id)
    planning_status = Planning_data.plan_status(id)
    for i in planner:
        plan = int(i.planner)
        flag = i.flag
    if plan == current_user.id:
        if planning_status.flag =='4':
            return redirect(url_for('app.home'))
    elif menber_status.flag == '3':
        return redirect(url_for('app.home'))
    
    #プロジェクトフラグが「3」の時、評価画面に遷移
    if flag == '3' or flag == '4':
        print(planning_status.flag)
        html = 'evaluation.html'
        member = Planning_menber.plan_member(id)
        member_len = len(member)
        print(member)
        print(member_len)
        current = str(current_user.id)
        return render_template(html,id=id,plan=plan,member=member,member_len=member_len,current=current)
    #プロジェクトメンバーか企画者ならば、プランチャットに遷移
    if check > 0 or plan == current_user.id:
        html = 'plan_chat.html'
        return render_template(html,lists=lists,id=id,plan=plan)
    return redirect(url_for('app.home'))

#企画のフラグを終了にする。（3）
@bp.route('/end_plan', methods=["POST"])
@login_required
def end_plan():
    id = request.form.get('id')
    Planning_data.change_flag(id,'3')
    db.session.commit()
    print(id)
    return redirect(url_for('app.plan_chat'))
    
#チャット書き込み処理
@bp.route('/plan_chat_up', methods=["POST"])
@login_required
def plan_chat_up():
    id = request.form.get('ID')
    Name_id = request.form.get('Name_id')
    comment = request.form.get('comment')
    chat = Planning_chat(
        plan_id=id,
        member_id = Name_id,
        comment = comment
    )
    chat.add_plan_chat()
    db.session.commit()
    return redirect(url_for('app.plan_chat')+'?ID='+id)

#評価ページ処理
@bp.route('/planning_evaluation', methods=["POST"])
@login_required
def planning_evaluation():
    planning_evaluation = request.form.get("planning_number")
    id = request.form.get("id")
    planning_comment = request.form.get("planning_comment")
    #企画への評価
    add_plan_evaluation = Plan_evaluation(
        plan_id = id,
        user_id = current_user.id,
        evaluation = planning_evaluation,
        comment = planning_comment
    )
    add_plan_evaluation.evaluation_add()
    db.session.commit()
    #企画者への評価
    planner = Planning_data.select_planner(id)
    for i in planner:
        plan = i.planner
    if current_user.id != plan:
        print(plan)
        user_add = User_evaluation(
            plan_id = id,
            receiver = plan,
            sender = current_user.id,
            evaluation = request.form.get("planner_number"),
            comment = request.form.get("planner_comment")
        )
        user_add.user_evaluation_add()
        db.session.commit()
    member = Planning_menber.plan_member(id)
    print(planning_evaluation,planning_comment)
    print(len(member))
    #メンバーの評価
    if len(member) > 0:
        for i in member:
            m = request.form.get(i.member_id + "_number")
            comment = request.form.get(i.member_id + "_comment")
            user_add = User_evaluation(
            plan_id = id,
            receiver = request.form.get(i.member_id),
            sender = current_user.id,
            evaluation = request.form.get(i.member_id + "_number"),
            comment = request.form.get(i.member_id + "_comment")
        )
            print(m)
            print(comment)
    if str(current_user.id) != plan:
        Planning_menber.menber_flags(id,current_user.id,"3")
        db.session.commit()
    else:
        Planning_data.change_flag(id,"4")
        db.session.commit()
    return redirect(url_for('app.plan_chat')+'?ID='+id)
    

#企画詳細ページの処理
@bp.route('/details')
def details():
    if request.method == 'GET':
        id = request.args.get('ID')
    lists = Planning_data.id_serect(id)
    comment = Comment_data.select_comment_date(id)
    menber = Planning_menber.plan_member(id)
    if current_user.is_authenticated:
        flag_1 = Message_data.application_confirmation(id,current_user.id)
        print(flag_1)
        # 企画タグを,ごとに区切りリストに登録
    for i in lists:
        planning_tag = i.taglist.split(',')
        planner_id = int(i.planner)
        flag = i.flag
    html = 'details.html'
    return render_template(html,tag=tagu,course_cr=course_cr,course_ds=course_ds,
    course_mu=course_mu,course_it=course_it,course_tc=course_tc,lists=lists,planning_tag=planning_tag,id=id,comment=comment,planner_id=planner_id,
    menber_list=menber,flag=flag,flag_1=flag_1)

#動作確認
@bp.route('/practic')
def practic():
    if request.method == 'GET':
        id = request.args.get('ID')
    lists = Planning_data.id_serect(id)
    menber = Planning_menber.plan_menber(id)
    print(menber)
        # 企画タグを,ごとに区切りリストに登録
    for i in lists:
        planner_id = int(i.planner)
    html = '練習.html'
    return render_template(html,tag=tagu,lists=lists,menber=menber,id=id,planner_id=planner_id)

@bp.route('/practic_end', methods=["POST"])
def practic_end():
    id = request.args.get('ID')
    menber = Planning_menber.plan_menber(id)
    for i in menber:
        print(i.member_id)
        recipient_name_id = request.form.get(2)
        print(recipient_name_id)
    return redirect(url_for('app.practic')+'?ID='+id)


@bp.route('/deadline')
@login_required
def deadline():
    id = request.args.get('ID')
    Planning_data.change_flag(id,"1")
    db.session.commit()
    return redirect(url_for('app.details')+'?ID='+id)

#申請メッセージの送信
@bp.route('/send_message', methods=["POST"])
@login_required
def send_message():
    id = request.form.get('ID')
    recipient_name_id = request.form.get('recipient_name_id')
    message = request.form.get('message-text')
    sender_name_id = request.form.get('sender_name_id')
    message_add = Message_data(
        plan_id=id,
        recipient_name_id = recipient_name_id,
        sender_name_id = sender_name_id,
        message = message
    )
    menber = Planning_menber(
        plan_id = id,
        member_id = current_user.id,
        flag = '0'
    )
    menber.menber_add()
    db.session.commit()
    message_add.create_new_message()
    db.session.commit()
    return redirect(url_for('app.details')+'?ID='+id)

@bp.route('/message_details')
@login_required
def message_details():
    id = request.args.get('ID')
    message = Message_data.details_message(id)
    print(message)
    return render_template('message_details.html',message=message)

@bp.route('/plan_request_ok')
@login_required
def plan_request_ok():
    flag = '1'
    id = request.args.get('ID')

Documents/GitHub/graduation/卒業制作 2020_10_29/flaskr/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>
    {{ field.label }}
    <dd>
        {{ field(**kwargs) | safe }}
        {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </dd>
</dt>
{% endmacro %}

Documents/GitHub/graduation/卒業制作 2020_10_29/flaskr/templates/base1.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}FLASK SNS{% endblock %}</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{url_for('app.home')}}">
                ホーム
            </a>
            {% if current_user.is_authenticated %}
            <a class="navbar-brand" href="{{url_for('app.logout')}}">
                ログアウト
            </a>
            <a class="navbar-brand" href="{{url_for('app.user')}}">
                ユーザ情報編集
            </a>
            {% else %}
            <a class="navbar-brand" href="{{url_for('app.login')}}">
                ログイン
            </a>
            <a class="navbar-brand" href="{{url_for('app.register')}}">
                登録
            </a>
            {% endif %}
        </nav>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

Documents/GitHub/graduation/卒業制作 2020_10_29/flaskr/templates/change_password.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワード変更画面 - {{ super() }}
{% endblock %}
{% block content %}
<h1>パスワード変更画面</h1>
<div class="row">
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

Documents/GitHub/graduation/卒業制作 2020_10_29/flaskr/templates/login.html
{% extends "base.html" %} {% block content %}
<div class="main">

    <section class="module">
        <div class="container">
            <div class="row">
                <div class="col-sm-5 col-sm-offset-1 mb-sm-40">
                    <h4 class="font-alt">Login</h4>
                    <hr class="divider-w mb-10">
                    <div class="login-form">
                        <form action="/login" method="POST">
                            <div class="form-group">
                                <input class="form-control" id="email" type="text" name="email" required="required" placeholder="email">
                            </div>
                            <div class="form-group">
                                <input class="form-control" id="password" type="password" name="password" required="required" placeholder="password">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-round btn-b">Login</button>
                            </div>
                        </form>
                    </div>
                    <a href="{{url_for('app.forgot_password')}}">
                        パスワードを忘れた場合
                    </a>
                </div>
                <div class="col-sm-5">
                    <h4 class="font-alt">Register</h4>
                    <hr class="divider-w mb-10">
                    <form class="form" action="/register" method="POST">
                        <div class="form-group">
                            <input class="form-control" id="E-mail" type="text" name="email" placeholder="Email" />
                        </div>
                        <br><br>
                        <div class="form-group">
                            <button class="btn btn-block btn-round btn-b">Register</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

Documents/GitHub/graduation/卒業制作 2020_10_29/flaskr/templates/message_details.html
{% extends "base.html" %} {% block content %}
<div class="main">
    <section class="module-small">
        <div class=".container note">
            <div class="container">
                {% for i in message%}
                <h2><i class="far fa-lightbulb"></i><span>プロジェクト名</span></h2>
                <div class="post-header font-alt">
                    <h1 class="post-title">{{i.title}}</h1>
                </div>
                <h4 class="comment-title font-alt">送信者</h4>
                <div class="comment clearfix">
                    <p>{{i.username}}</p>
                </div>
                <h4 class="comment-title font-alt">内容</h4>
                <div class="box25">
                    <p>{{i.message}}</p>
                </div>
                <p></p>
                {% if i.flag == "0" %}
                <h4 class="comment-title font-alt">メンバーにしますか？</h4>
                <a href="/plan_request_ng?ID={{i.id}}" class="btn btn-flat1"><span>却下</span></a>
                <a href="/plan_request_ok?ID={{i.id}}" class="btn btn-flat"><span>承諾</span></a> {% elif i.flag == "1" %}
                <h3>既に承諾されています。</h3>
                <a href="/plan_request?ID={{i.id}}" class="btn btn-flat1"><span>取り消す</span></a> {% elif i.flag == "2" %}
                <h3>既に却下されています。</h3>
                <a href="/plan_request?ID={{i.id}}" class="btn btn-flat1"><span>取り消す</span></a> {% endif %} {% endfor %}
            </div>
        </div>
    </section>
</div>


{% endblock %}

Documents/GitHub/graduation/卒業制作 2020_10_29/flaskr/templates/message_list.html
{% extends "base.html" %} {% block content %}
<div class="main">
    <section class="module-small">
        <div class="container">
            <h4 class="font-alt">受信したメッセージ</h4>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>プロジェクトタイトル</th>
                        <th>送信者</th>
                        <th>内容</th>
                        <th>日付</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in message_list%}
                    <tr data-href="/message_details?ID={{i.id}}">
                        <td>{{i.title}}</td>
                        <td>{{i.username}}</td>
                        <td>{{i.message}}</td>
                        <td>{{i.create_at}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
</div>
<script src="./jquery.min.js"></script>
<script>
    jQuery(function($) {
        $('tbody tr[data-href]').addClass('clickable').click(function() {
            window.location = $(this).attr('data-href');
        }).find('a').hover(function() {
            $(this).parents('tr').unbind('click');
        }, function() {
            $(this).parents('tr').click(function() {
                window.location = $(this).attr('data-href');
            });
        });
    });
</script>
{% endblock %}

Documents/GitHub/graduation/卒業制作 2020_10_29/flaskr/templates/participation_list.html
{% extends "base.html" %} {% block content %}

<section class="module">
    <div class="container-fluid" style="margin-left: 3%;">
        <h1 class="widget-title font-alt">自身が参加しているプロフェクト</h1>
        {% if not lists %}
        <h3>現在参加している企画はありません</h3>
        {% else %}
        <dev class="row row-eq-height">
            {% for i in lists %}
            <div class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
                <div class="post">
                    <div class="post-thumbnail">
                        {% if not i.image %}
                        <a href="/plan_chat?ID={{i.id}}"><img src="static/planning_image/nc33060.png" alt="説明書き" width="800" height="460" class="img-fluid img_list"></a>
                        {% else %}
                        <a href="/plan_chat?ID={{i.id}}"><img src="static/planning_image/{{i.id}}/{{i.image}}" alt="説明書き" width="800" height="460" class="img-fluid img_list"></a>
                        {% endif %}
                    </div>
                    <div class="post-header font-alt">
                        {% if i.title | length >= 30 %}
                        <h2 class="post-title"><a href="/plan_chat?ID={{i.id}}">{{i.title[:30]}}...</a></h2>
                        {% else %}
                        <h2 class="post-title"><a href="/plan_chat?ID={{i.id}}">{{i.title}}</a></h2>
                        {% endif %}
                        <div class="post-meta">&nbsp;<a href="#">{{i.username}}</a>&nbsp;{{i.create_at}}
                        </div>
                    </div>
                    <div class="post-entry">
                        {% if i.contents | length >= 50 %}
                        <p>{{i.contents[:50]}}...</p>
                        {% else %}
                        <p>{{i.contents}}</p>
                        {% endif %}
                    </div>
                    <div class="post-more"><a class="more-link" href="#">Read more</a></div>
                </div>
            </div>
            {% endfor %}
        </dev>
        {% endif %}
    </div>
    </div>
</section>
{% endblock %}

Documents/GitHub/graduation/卒業制作 2020_10_29/flaskr/templates/plan_chat.html
{% extends "base.html" %} {% block content %}
<div class="main">
    <section class="module-small">
        <div class="container">
            <h1></h1>

            <!--コメント欄-->
            <div class="comment-form">
                <h4 class="comment-form-title font-alt">コメント</h4>
            </div>
            {% for c in lists%}
            <div class="box25">
                <div class="row" style="margin-bottom: -3px;">
                    <div class="col-sm-1">
                        {%if not c.picture_path %}
                        <img class="user_icon" src="static/planning_image/nc33060.png"></a>
                        {%else%}
                        <img class="user_icon" src="static/user_image/{{current_user.id}}/{{c.picture_path}}"></a>
                        {%endif%}
                    </div>
                    <font size="5">{{c.username}}</font>&nbsp;{{c.create_at}}
                </div>
                <hr class="cp_hr03" style="margin-top: -3px;" />
                <div style="width: 50;">
                    <p style="padding-left: 100px; word-wrap:break-all;">{{c.comment}}</p>
                </div>
            </div>
            <p></p>
            {% endfor %}
            <!--コメント書き込み処理-->
            <div class="comment-form">
                <h4 class="comment-form-title font-alt">書き込む</h4>
                <form method="post" action="/plan_chat_up">
                    <div class="form-group">
                        <input type="hidden" name="ID" value="{{id}}">
                        <input type="hidden" name="Name_id" value="{{current_user.id}}">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" id="comment" name="comment" rows="4" placeholder="Comment"></textarea>
                    </div>
                    <button class="btn btn-round btn-d" type="submit">書き込む</button>
                </form>
                <!--プロジェクトを終了ボタン-->
                {% if plan == current_user.id %}
                <nav><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Modal1">プロジェクトを終了する</button></nav>
                <div class="modal fade" id="Modal1" tabindex="-1" aria-labelledby="Modal1" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-center">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="Modal1">メッセージを送る</h5>
                            </div>
                            <div class="modal-body">
                                <form class="form" role="form" action="/end_plan" method="POST" enctype="multipart/form-data">
                                    <h3>一度終了すると戻すことが出来ません。</h3>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                                        <input type="hidden" name="id" value={{id}}>
                                        <button class="btn btn-round btn-d" type="submit"><i class="fa fa-paper-plane-o"></i>終了する。</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </section>
</div>


{% endblock %}

Documents/GitHub/graduation/卒業制作 2020_10_29/flaskr/templates/register.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザ登録 - {{ super() }}
{% endblock %}
{% block content %}
<h1>ユーザ情報登録画面</h1>
<div class="row">
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.username) }}
        {{ render_field(form.email) }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

Documents/GitHub/graduation/卒業制作 2020_10_29/flaskr/templates/search.html
{% extends "base.html" %} {% block content %}
<!--ここより上はmainと同じ-->
<section class="module">
    <div class="container-fluid" style="margin-left: 3%;">
        <h1 class="widget-title font-alt">募集中の企画 {{tag or ''}}</h1>
        <div class="widget" style="margin-left: 80%;">
            <form role="form" action="/search" method="GET">
                <div class="search-box">
                    <input class="form-control" type="text" placeholder="検索" name="tags" />
                    <button class="search-btn" type="submit"><i class="fa fa-search"></i></button>
                </div>
            </form>
        </div>
        <div class="table-responsive">
            <div class="widget">
                <div class="tags font-serif">
                    {% for i in taglist %}
                    <a href="/search?tags={{i}}">{{i}}</a> {% endfor %}
                </div>
            </div>
        </div>
        <dev class="row row-eq-height">
            {% for i in lists %}
            <div class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
                <div class="post">
                    <div class="post-thumbnail">
                        {% if not i.image %}
                        <a href="/details?ID={{i.id}}"><img src="static/planning_image/nc33060.png" alt="説明書き" width="800" height="460" class="img-fluid img_list"></a>
                        {% else %}
                        <a href="/details?ID={{i.id}}"><img src="static/planning_image/{{i.id}}/{{i.image}}" alt="説明書き" width="800" height="460" class="img-fluid img_list"></a>
                        {% endif %}
                    </div>
                    <div class="post-header font-alt">
                        {% if i.title | length >= 30 %}
                        <h2 class="post-title"><a href="/details?ID={{i.id}}">{{i.title[:30]}}...</a></h2>
                        {% else %}
                        <h2 class="post-title"><a href="/details?ID={{i.id}}">{{i.title}}</a></h2>
                        {% endif %}
                        <div class="post-meta">&nbsp;<a href="#">{{i.username}}</a>&nbsp;{{i.create_at}}
                        </div>
                    </div>
                    <div class="post-entry">
                        {% if i.contents | length >= 50 %}
                        <p>{{i.contents[:50]}}...</p>
                        {% else %}
                        <p>{{i.contents}}</p>
                        {% endif %}
                    </div>
                    <div class="post-more"><a class="more-link" href="#">Read more</a></div>
                </div>
            </div>
            {% endfor %}
        </dev>
    </div>
    </div>
    <!--右下のボタン-->
    <div id="fixed">
        <a href="{{url_for('app.forms')}}" class="btn btn-malformation">企画する</a>
    </div>
</section>
{% endblock %}

Documents/GitHub/graduation/卒業制作 2020_10_29/flaskr/templates/update.html
{% extends "base.html" %} {% block content %}
<section class="module">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
                <h4 class="font-alt mb-0">企画を更新する</h4>
                <hr class="divider-w mt-10 mb-20"> {% for i in plan %}
                <form class="form" role="form" action="/updated?ID={{i.id}}" method="POST" enctype="multipart/form-data">
                    <div class="form-group">
                        <input class="form-control input-lg" type="text" name="title" placeholder="企画名" value={{i.title}} />
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" rows="5" name="contents" placeholder="概要">{{i.contents}}</textarea>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" rows="4" name="application" placeholder="募集要項">{{i.application}}</textarea>
                    </div>
                    <!--<div class="form-group">
                        <input type="file" name="image" accept="image/jpeg">
                    </div>-->
                    <div class="form-group">
                        <textarea class="form-control" rows="7" name="taglist" placeholder="タグ 複数ある場合は「,」で区切りで入力してください。">{{i.taglist}}</textarea>
                    </div>
                    <button class="btn btn-primary btn-round" type="submit"><i class="fa fa-paper-plane-o"></i> 更新</button>
                </form>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

Documents/GitHub/graduation/卒業制作 2020_10_29/flaskr/templates/user.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザ情報編集画面 - {{ super() }}
{% endblock %}
{% block content %}

<div class="row">
    <div class="col-lg-8 offset-lg-4">
    {% for message in get_flashed_messages() %}
    {{ message }}
    {% endfor %}
    </div>
    <div class="col-lg-4 offset-lg-2">
        {% if current_user.picture_path %}
        <img src="{{url_for('static', filename=current_user.picture_path)}}">
        {% endif %}
    </div>
    <div class="col-lg-4 offset-lg-2">
        <form method="POST" enctype="multipart/form-data">
            {{form.csrf_token}}
            {{render_field(form.username, value=current_user.username)}}
            {{render_field(form.email, value=current_user.email )}}
            {{render_field(form.picture_path) }}
            {{form.submit()}}
        </form>
        <a href="{{url_for('app.change_password')}}">パスワードを変更する</a>
    </div>

</div>
{% endblock %}